name: ACR

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v4
    
    - name: Docker build
      run: docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/${{ secrets.ACR_NAME }} .
    
    - name: ACR Login
      uses: azure/docker-login@v2
      with:
        login-server: ${{ secrets.ACR_NAME }}.azurecr.io
        username: ${{ secrets.ACR_NAME }}
        password: ${{ secrets.ACR_PASS }}

    - name: Push image
      run: docker push ${{ secrets.ACR_NAME }}.azurecr.io/${{ secrets.ACR_NAME }}

    - name: Deploy Function App
      run: |
        az functionapp config container set \
          --name ${{ secrets.FUNCTION_APP_NAME }} \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --docker-custom-image-name "${{ secrets.ACR_NAME }}.azurecr.io/${{ secrets.ACR_NAME }}:latest"
