name: ACR

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
    
    - name: Run a simple script
      run: echo "Hello, GitHub Actions!"